config/routes.rb
Rails.application.routes.draw do
  get "/reports", to: "shifts#reports"
  get "/userReport/:user_id", to: "shifts#userReports"
  post "/approve_request", to: "requests#approve"
  post "/deny_request", to: "requests#deny"
  post "/assign_shift", to: "shifts#assign_shift"
  post "/create_shift_template", to: 'shift_template#create'
  get "/assigned_shifts/:id", to: "users#assigned_shifts", as: :assigned_shifts
  post "/change_shift", to: 'requests#change_shift', as: :change_shift
  post "/make_shift_available", to: 'requests#make_shift_available', as: :make_shift_available
  patch "/pick_up_shift/:id", to: 'requests#pick_up_shift', as: :pick_up_shift
  patch "/give_shift/:id", to: 'requests#give_shift', as: :give_shift
  patch "/approve_shift/:id", to: 'requests#approve_shift', as: :approve_shift


  devise_scope :user do
    get '/signup', to: 'registrations#new'
    post '/new_user', to: 'registrations#create', as: :create_user
    get '/add_employee', to: 'registrations#new_employee', as: :new_employee
    post '/create_employee', to: 'registrations#create_employee', as: :create_employee
  end

  devise_for :users

  resources :requests

  get '/users/sign_in', to: 'sessions#create', as: 'login'

  get 'company/new'

  get '/dashboard', to: 'welcome#dashboard', as: :dashboard

  root "welcome#splash"
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def splash
    if user_signed_in?
        render 'admin'
    else
        render 'index'
    end
  end

  def dashboard
    render 'admin'
  end

    def requests
    render 'admin'
  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
  def time_options
    am_options = []
    increment = 0
    (1..11).each do |i|
      am_options << ["#{i}:00am", 60 + increment]
      am_options << ["#{i}:30am", 90 + increment]
      increment += 60
    end
    am_options = [["12:00am", 0] ,["12:30am", 30]] + am_options
    pm_options = []
    increment_pm = 720
    (1..11).each do |i|
      pm_options << ["#{i}:00pm", 60 + increment_pm]
      pm_options << ["#{i}:30pm", 90 + increment_pm ]
      increment_pm += 60
    end
    pm_options = [["12:00pm",720],["12:30pm",750]] + pm_options
    am_options + pm_options 
  end
end

app/views/welcome/add_employee.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Document</title>
    <link rel="stylesheet" href="css/main.css">
    <link rel="stylesheet" href="css/animate.css">
    <link rel="stylesheet" href="css/carousel.css">
    <link rel="stylesheet" href="css/signup_form.css">
</head>

<body>
    <!-- main section for the form -->
    <div class="container tall">
        <div class="signup_container">
        <%= form_for(resource, as: resource_name, url: create_employee_path, html: {class: "form01"}) do |f| %>
        <h2 class="label">Add Employee Information</h2>
            <span class="label">Email</span>
            <%= f.email_field :email, class: "g_inpt"  %>
            <span class="label">First Name:</span>
            <%= f.text_field :first_name, class: "g_inpt" %>
            <span class="label">Last Name:</span>
            <%= f.text_field :last_name, class: "g_inpt"  %>
            <span class="label">Password:</span>
            <%= f.password_field :password, class: "g_inpt" %>
            <span class="label">Password Confirmation:</span>
            <div class="clear"></div>
            <%= f.password_field :password_confirmation, class: "g_inpt" %>
            <span class="label">Make this Employee an Admin</span>
            <%= f.check_box :is_admin, class: "g_inpt"  %>
            <%= f.hidden_field(:company_id, value: current_user.company_id) %>
            <button type="sumbit" class="input_btn" value="signup">Sign up</button><br><br>
            <a href="/" value="cancel">Cancel</a>
            <!-- <input type="button" class="sub_btn" value="submit"> -->
        <% end %>
        </div>
    </div>

    <!-- javascript -->
    <script src="js/jquery.min.js"></script>
    <script src="js/carousel.js"></script>
    <script src="js/main.js"></script>
</body>

</html>

app/views/welcome/admin.html.erb
<div class="container_dash tall">
    <div class="left_cont">
        <%= image_tag current_user.avatar.url(:thumb), :class=>"avatar" %>
        <span class="admin_name" ><%=current_user.first_name %> <%=current_user.last_name %></span>
        <% if current_user.is_admin %>
            <div class="employeesList">
                <% current_user.company.users.each do |employee|%>
                    <% if employee.has_requests_pending_approval %>
                        <div class="employee hasPendingRequest">
                            <input type="hidden" value=<%= employee.id %> class="employeeID">
                            <div class='employeeName'><%= employee.first_name %> </div>
                            <div class='employeeRequestNotifier'>Request Pening Approval</div>
                            <div class='employeeRequests' hidden>
                                <% employee.request_pending_approval.each do |request|  %>
                                <div class="employeeRequest">
                                    <div class="requestType"><%= request.type_string %> </div>
                                    <div class="requestShift">
                                        <%= request.shift.time_string %> on <%= request.shift.date %>
                                    </div>
                                    <div class="requestReason">
                                        Reason: <%= request.reason %>
                                    </div>
                                    <button onclick="approveRequest(<%= request.id %>, this)">Approve</button>
                                    <button onclick="denyRequest(<%= request.id %>, this)">Deny</button>
                                </div>
                                <% end %>
                            </div>
                        </div>
                    <% else %>
                        <div class="employee">
                            <div class='employeeName'><%= employee.first_name %></div>
                            <input type="hidden" value=<%= employee.id %> class="employeeID">
                        </div>
                    <% end %>
                <% end %>
            </div>
            <div id="requestBox" hidden>
                <h5 class="request_header"></h5>
                <%= form_for :request, url: change_shift_path do |f| %>
                    <%= f.hidden_field(:requester_id, value: current_user.id) %>
                    <%= f.hidden_field(:availability, value: false) %>
                    <%= f.hidden_field(:shift_id, value: 1) %>
                    <%= f.text_area :reason, {class: "text_area_box", placeholder: "Please type your reason in here!"} %>
                    <button type="submit" class="btn_shift_change">submit</button>
                <% end %>

            </div>
            <div class="date_box" id='external-events'>
                <h4 class="textarea">Shifts</h4>
                <div class="shiftTemplatesList">
                <% current_user.company.shift_templates.each do |shift_template| %>
                    <div class='external-event' data-shift-template-id="<%=shift_template.id  %>"><%=shift_template.time_string  %></div>
                <% end %>
                </div>
                <button id="newShift" class='btn addShift' onclick="showShiftForm()">New Shift Type</button>
                <div class="shiftTemplateForm" hidden>
                    <h4>Create Shift Type</h4>
                    <label class="start_label">Start Time</label>
                    <select id="shiftTempStartTime">
                        <%= options_for_select(time_options, '450') %>
                    </select>
                    <br>
                    <label class="end_label">End Time</label>
                    <select id="shiftTempEndTime">
                        <%= options_for_select(time_options, '1050') %>
                    </select>
                    <br>
                    <button id="createShift" class='btn addShift' onclick="createShift()">Add</button>
                    <button id="createShift" class='btn addShift' onclick="cancelCreateShift()">Cancel</button>
                </div>
            </div>
        <% end %>
        <div id="requestBox" hidden>
            <h5 class="request_header"></h5>
            <%= form_for :request, url: change_shift_path do |f| %>
                <%= f.hidden_field(:requester_id, value: current_user.id) %>
                <%= f.hidden_field(:availability, value: false) %>
                <%= f.hidden_field(:shift_id, value: 1) %>
                <%= f.text_area :reason, {class: "text_area_box", placeholder: "Please type your reason in here!"} %>
                <button type="submit" class="btn_shift_change">submit</button>
            <% end %>
        </div>
        <div id="availabilityBox" hidden>
            <h5 class="availability_header"></h5>
            <%= form_for :request, url: make_shift_available_path do |f| %>
                <select id="shiftTempOptions" name='shift_template_id'>
                    <%= options_for_select(current_user.company.shift_templates.collect{|shift| [ shift.time_string,shift.id]}) %>
                </select>
                <%= f.hidden_field(:accepter_id, value: current_user.id) %>
                <%= hidden_field_tag(:date, nil, class: "availabilityDate") %>
                <%= f.hidden_field(:availability, value: true) %>
                <%= f.text_area :reason, {class: "text_area_box", placeholder: "Please type your reason in here!"} %>
                <button type="submit" class="btn_shift_change">submit</button>
            <% end %>
        </div>
        <% if current_user.has_pending_requests %>
            <div class="pendingRequests_one">
                <h4>Pending Requests</h4>
                <% current_user.pending_requests.each do |request|%>
                    <div class="pendingRequests">
                        <% if request.admin %>
                            <div class="approvedRequest"><%= request.approved_string %></div>
                        <% else %>
                            <div class="requestPendingApproval"><%= request.approved_string %></div>
                        <% end %>

                        <div class="pendingRequestType"><%= request.type_string %> </div>
                        <div class="pendingRequestDate"><%= request.shift.date.to_formatted_s(:long) %></div>
                        <div class="pendingRequestTime"><%= request.shift.time_string %></div>
                        <div class="pendingRequestReason"><%= request.reason %></div>
                    </div>
                <% end %>
            </div>
        <% end %>

    </div>
    <div class="right_cont">
        <div class="notify" id="note">
            Recent Notification
        </div>
        <input type="hidden" value=<%= current_user.id %> id="employeeID">
        <div id='calendar'></div>
            <div class="shiftsForPickUp">
                <h4>Shifts for Pick Up</h4>
                <% current_user.shifts_for_pick_up.each do |request| %>
                    <% if !(current_user.shifts_array.include? "#{request.shift.shift_template_id} - #{request.shift.date}") %>
                        <div class="pickUpShift">
                            <hr class="requestSplit">
                            <div class="pendingRequestUser"><%= request.requester.first_name %> </div>
                            <div class="pendingRequestDate"><%= request.shift.date.to_formatted_s(:long) %></div>
                            <div class="pendingRequestTime"><%= request.shift.time_string %></div>
                            <div class="pendingRequestReason"><%= request.reason %></div>
                        </div>
                        <%= form_for request, url: pick_up_shift_path(request.id) do |f| %>
                            <%= f.hidden_field(:accepter_id, value: current_user.id) %>
                            <%= f.submit value:"Pick Up Shift" %>
                        <% end %>
                    <% end %>
                <% end %>
            </div>
            <div class="shiftsToGive">
                <h4>Shifts available to give</h4>
                <% current_user.shifts_to_give.each do |request| %>
                    <% if current_user.shifts_array.include? "#{request.shift.shift_template_id} - #{request.shift.date}" %>
                        <div class="pickUpShift">
                            <hr class="requestSplit">
                            <div class="pendingRequestUser"><%= request.accepter.first_name %> </div>
                            <div class="pendingRequestDate"><%= request.shift.date.to_formatted_s(:long) %></div>
                            <div class="pendingRequestTime"><%= request.shift.time_string %></div>
                            <div class="pendingRequestTime"><%= request.shift.id %></div>
                            <div class="pendingRequestReason"><%= request.reason %></div>
                            <%= form_for request, url: give_shift_path(request.id) do |f| %>
                                <%= f.hidden_field(:requester_id, value: current_user.id) %>
                                <%= f.submit value:"Give Shift" %>
                            <% end %>
                        </div>
                    <% end %>
                <% end %>
            </div>
        </div>
        <div style='clear:both'></div>
    </div>
</div>

<script type="text/javascript">
    var userID = <%= current_user.id %>,
        companyID = <%= current_user.company.id %>,
        timeOptions = <%= raw current_user.company.shift_templates.collect{|shift| [shift.id, shift.time_string] } %> ;

</script>

app/views/welcome/index.html.erb
<div class="carousel_text_cont" onclick='runIt()'>
        <div class="slogan_blocks">
            <div class="box">
                <p class="text">Simple</p>
            </div>
            <div class="box">
                <p class="text">Convenient</p>
            </div>
            <div class="box">
                <p class="text">Reliable</p>
            </div>
        </div>
        <p class="poster"><strong>Sheduling</strong> made <strong>easier</strong>.</p>
    </div>
<div id='carousel_container'>
    <div id='left_scroll'>
        <%= image_tag("arrow_left.png") %>
    </div>
    <div id='carousel_inner'>
        <ul id='carousel_ul'>
            <li>
                <a href='#'>
                    <%= image_tag 'coffee.png' %>
                </a>
            </li>
            <li>
                <a href='#'>
                    <%= image_tag 'balance.png' %>
                </a>
            </li>
            <li>
                <a href='#'>
                    <%= image_tag 'metro.png'%>
                </a>
            </li>
        </ul>
    </div>
    <div id='right_scroll'>
        <%= image_tag("arrow_right.png") %>
    </div>
</div>

<div class="container">
   <div class="content-left">
        <p class="big">Welcome to Shiftable</p>
        <p>Shiftable allows employess to switch shifts with other employees when needed. We make swiching shifts easy for employees and shift-managers.</p>
        <p class="big">About Us</p>
        <p>At Shiftable, we believe that requesting shift change should be <strong>easy, convenient, and reliable.</strong>. We understand the importance of having a dependable online scheduling tool in today's always-connected world. </p>
        </br>
        <h4>Shiftable efficiently automates:</h4>
        <ul>
            <li>Shift-picks by employees</li>
            <li>Shift-change requests by employees</li>
            <li>Manager approval and reassignments</li>
            <li>Manager's ability to add new employees and shifts</li>
        </ul>
    </div>
    <div class="content-right">
       <p>Shiftable is a group project built on Ruby on Rails & JavaScript for General Assembly's Web Development Immersive 2 in Washington, DC.</p><br/><p> Team members include:
        <ul class='team'>
            <li><a href="https://github.com/eerrad213">Erwin Rosas</a><br>as the Back-end lead,</li>
            <li><a href="https://github.com/Babakadam121">Babak Pouradam</a><br>as the Front-end lead</li>
            <li><a href="https://github.com/Eldwick">James Jalandoni</a><br>as Project Lead </li>
            <li><a href="https://github.com/ruchimk">Ruchi Malik</a><br>as Project Manager.</li>
        </ul>
    </div>
</div>

app/views/welcome/requests.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>

<body>
    <div class="container_dash tall">
        <div class="left_cont">
            <%= image_tag current_user.avatar.url(:thumb), :class=>"avatar" %>
            <span class="admin_name" ><%=current_user.first_name %> <%=current_user.last_name %></span>
        </div>

        <div class="right_cont">
            <div class="requestsList">
                <h2>Requests for <%=current_user.company.name %></h2>
            </div>
            <div class="employeesList">
                <% current_user.company.users.each do |employee|%>
                    <% if employee.has_requests_pending_approval %>
                        <div class="employee hasPendingRequest">
                            <input type="hidden" value=<%= employee.id %> class="employeeID">
                            <div class='employeeName'><%= employee.first_name %> </div>
                            <div class='employeeRequestNotifier'>All User Requests</div>

                            <div class='employeeRequests' hidden>Created Requests
                                <% employee.made_requests.each do |request|  %>
                                <div class="employeeRequest">
                                <hr class="requestSplit">
                                    <div class="requestShift">
                                        <%= request.shift.time_string %> on <%= request.shift.date %> for request: <%= request.id %>
                                    </div>
                                    <div class="requestReason">
                                        Reason: <%= request.reason %>
                                    </div>
                                    <div class="requestReason">
                                        Requester: <%= request.requester ? request.requester.first_name : "Not Yet Set" %>
                                    </div>
                                    <div class="requestReason">
                                        Accepter: <%= request.accepter ? request.accepter.first_name : "Not Accepted"  %>
                                    </div>
                                </div>
                                <% end %>
                            </div>
                            <div class='employeeRequests' hidden>Available Requests
                                <% employee.accepted_requests.each do |request|  %>
                                <div class="employeeRequest">
                                <hr class="requestSplit">
                                    <div class="requestShift">
                                        <%= request.shift.time_string %> on <%= request.shift.date %> for request: <%= request.id %>
                                    </div>
                                    <div class="requestReason">
                                        Reason: <%= request.reason %>
                                    </div>
                                    <div class="requestReason">
                                        Requester: <%= request.requester ? request.requester.first_name : "Not Yet Set" %>
                                    </div>
                                    <div class="requestReason">
                                        Accepter: <%= request.accepter ? request.accepter.first_name : "Not Accepted"  %>
                                    </div>
                                </div>
                                <% end %>
                            </div>
                            <div class='employeeRequests' hidden>Approved Requests
                                <% employee.approved_requests.each do |request|  %>
                                <div class="employeeApprovedRequest">
                                <hr class="requestSplit">
                                    <div class="requestShift">
                                        <%= request.shift.time_string %> on <%= request.shift.date %> for request: <%= request.id %>
                                    </div>
                                    <div class="requestReason">
                                        Reason: <%= request.reason %>
                                    </div>
                                    <div class="requestReason">
                                        Requester: <%= request.requester ? request.requester.first_name : "Not Yet Set" %>
                                    </div>
                                    <div class="requestReason">
                                        Accepter: <%= request.accepter ? request.accepter.first_name : "Not Accepted"  %>
                                    </div>
                                    <div class="requestReason">
                                        Approved By: <%=request.admin ?  request.admin.first_name : "Not yet Approved" %>
                                    </div>
                                </div>
                                <% end %>
                            </div>
                        </div>
                    <% end %>
                <% end %>
            </div>
        </div>
            <div class="line"></div>
    </div>
    <script type="text/javascript">
        var userID = <%= current_user.id  %>,
            companyID = <%= current_user.company.id  %>;
    </script>
    <!-- javascript -->
</body>

</html>

app/views/welcome/signup_page.html.erb
<!-- main section for the form -->
<div class="container tall">
    <div class="signup_container">
    <%= form_for(resource, as: :user, url: create_user_path, html: {class: "form01"}) do |f| %>
    <%= devise_error_messages! %>
    <h2 class="label">Sign Up your Company</h2>
        <span class="label">Company Name:</span>
        <%= text_field_tag :company_name, nil, class: "g_inpt" %>
        <span class="label">Email</span>
        <%= f.email_field :email, class: "g_inpt"  %>
        <span class="label">First Name:</span>
        <%= f.text_field :first_name, class: "g_inpt" %>
        <span class="label">Last Name:</span>
        <%= f.text_field :last_name, class: "g_inpt"  %>
        <span class="label">Profile Picture:</span>
        <%= f.label :avatar , class: "g_inpt" %><br />
        <%= f.file_field :avatar %>
        <span class="label">Password:</span>
        <%= f.password_field :password, class: "g_inpt" %>
        <span class="label">Password Confirmation:</span>
        <div class="clear"></div>
        <%= f.password_field :password_confirmation, class: "g_inpt" %>
        <%= f.hidden_field(:is_admin, value: true) %>
        <%= f.submit "Sign up", class: "sub_btn" %>
        <%= link_to "Cancel", root_path, class: "cancel" %>
    <% end %>
    </div>
</div>